spring:
  application:
    name: nve-jdbc-processor-rabbit
  cloud:
    stream:
      bindings:
        input:
          destination: txf1
        output:
          destination: replies
          content-type: application/xml
  datasource:
    url: jdbc:postgresql://localhost:5432/nve
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10
      connection-timeout: 5000
  jpa:
    show-sql: true
      
jdbc:
  query: select returncode, messageid, messagetext, userexistsind, ssn4 from xtable(f_checkuser(?, ?))
  update: false

---
spring:
  profiles: local
  datasource:
    url: jdbc:postgresql://localhost:5432/nve
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    show-sql: true

jdbc:
  query: select returncode, messageid, messagetext, userexistsind, ssn4 from xtable(hr.f_checkuser(?, ?))